### ISSUE TITLE
how to reinstall it?

### ISSUE THREAD

**Issue by Scrubbys** [jbara2002/windows-defender-remover#1]
i uninstalled defender but now some programs are bugging out, any way to re install everything it deletes?

**Comment by jbara2002** [comment]
updating windows inplace with a iso image it re-adds defender if you remove with all packages. If you press N, re-run the script and press E.

**Comment by alejandro097** [comment]
which programs?

**Comment by jbara2002** [comment]
the script

**Comment by jbara2002** [comment]
@Scrubbys  and @alejandro097  Removal of Windows Defender is permanent, if you press y in opened script. To reinstall it, you must reinstalling Windows by upgrading OS in-place (with windows setup and etc).
If you pressed N, the defender app is disabled , and to enable windows defender protection you must re-run the script and press E.
