### ISSUE TITLE
How to keep Admin Elevation?

### ISSUE THREAD

**Issue by xwiz** [jbara2002/windows-defender-remover#10]
Is there a way to keep the admin elevation feature? I use an admin and non-admin accounts and after removing, I can no longer elevate my regular account to admin?

**Comment by jbara2002** [comment]
Yes, via registry.
Go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System and find EnableLUA put value 1 and reboot. If the setting is not change go to run write UserAccountControlSettings and drag level type of elevation on that.
