### ISSUE TITLE
system restore 

### ISSUE THREAD

**Issue by DukeJukemEG** [jbara2002/windows-defender-remover#11]
can we make the new system restore option opional? i have it permanently disabled to the point where i cant re enable it and the script throws and error because it can't access the system restore service. the removal script continues to run after it throws the error but the disable script just throws the error and reboots and im not sure if its doing anything.

**Comment by jbara2002** [comment]
In script. if check if the system restore service is available, if is not (i don't use System Restore too), it says its disabled or is not existed.
The script continues with the settings and removal, if a problem is expected on the script, you can specify more details.

**Comment by jbara2002** [comment]
I had remove the system restore part and recopiled the code. So, go to releases section and you'll see a version which is not creating system restore point.

**Comment by hubert3** [comment]
Option R in release 12.4.1 says it created a system restore point, but it doesn't actually do it

(I had not enabled System Protection before trying it)
