### ISSUE TITLE
Add GUI for Defender Remover

### ISSUE THREAD

**Issue by jbara2002** [jbara2002/windows-defender-remover#19]
Adding GUI for Remover, will be easier for users to access the content from the GUI.
This must be for testing starting for Jan 2023, and the release in March 2023.

**Comment by 20umi** [comment]
> Ne pare rău că întrerup această secțiune, vă rog să adăugați pentru a instala back windows defender? Nu pot actualiza Windows și sunt blocat ca 3 luni, poate puteți inversa scriptul de eliminare, astfel încât să îl putem "reinstala". TNX în avans

Once it has been removed, this application cannot reinstall windows defender. The solution is to repair windows using the bootable stick for installing the operating system.

**Comment by 20umi** [comment]
> Sorry to interrupt this section, can u please add to install back windows defender? i cant update windows and im stuck like 3months, maybe u can reverse removal script so we can maybe "reinstall" it. TNX in advance
Once it has been removed, this application cannot reinstall windows defender. The solution is to repair windows using the bootable stick for installing the operating system.
