### ISSUE TITLE
Use in case of bitlocker will result in UNMOUNTABLE BOOT VOLUME

### ISSUE THREAD

**Issue by wgetnz** [jbara2002/windows-defender-remover#22]
![2023-01-07_14-03-43](https://user-images.githubusercontent.com/62410571/211133929-ed54de39-d25f-4f68-bc8c-589b5a61613d.jpg)

22621.963.221202-2359.NI_RELEASE_SVC_PROD1_CLIENTPRO_OEMRET_X64FRE_ZH-CN

This caused me to lose all my data.......

**Comment by jbara2002** [comment]
The issue with bitlocker is known.

**Comment by jbara2002** [comment]
I will work for new hotfixes

**Comment by jbara2002** [comment]
fixed in 12.0!
