### ISSUE TITLE
Microsoft store bug?

### ISSUE THREAD

**Issue by ProphetxQc** [jbara2002/windows-defender-remover#26]
hi , dont know if the bug is from this but after use this , the microsoft store update not working anymore
![Capture d’écran 2023-01-17 071925](https://user-images.githubusercontent.com/118022466/212897384-0541892d-81c2-4bb8-a514-d8686e6802f5.png)

**Comment by jbara2002** [comment]
no, after working and tested this script, Microsoft Store is unaffected... so it's not from the script...
