### ISSUE TITLE
Can't disable defender.

### ISSUE THREAD

**Issue by LePeeManPog** [jbara2002/windows-defender-remover#27]
ok so like this is kinda my fault, in the past i had used a program (kmsauto) to disable my windows defender, but recently i wanted to test if something would get flagged by defender but i couldnt find what program i had used. I found this repo and i enabled defender thru this, but my virus & threat protection thingy is disabled so i cant stop real time protection from deleting this program automatically, so i can disable defender again and idk what to do.  (https://real.big-pp.club/ongodongod/afWMp6Cc)

**Comment by jbara2002** [comment]
First, run sfc /scannow and reboot.
After that re run the enabler part of the script again (you must have last version).

**Comment by jbara2002** [comment]
fixed in 12.0!
