### ISSUE TITLE
Notification pops up asking to  turn on windows security center service

### ISSUE THREAD

**Issue by Rinzler081** [jbara2002/windows-defender-remover#28]
I know I can ignore the notification but it makes me think that something else is still being triggered where it then generates that message. I ran disable defender on 11.1
Is there another service or something I can disable in task scheduler to prevent this?

**Comment by jbara2002** [comment]
the security center notification can be disabled in settings -> notifications. Normally the notification must not appear, thanks for noticing.

**Comment by jbara2002** [comment]
fixed in 12.0!
