### ISSUE TITLE
although i pressed "n", everything is removed and i cannot execute the programm again!

### ISSUE THREAD

**Issue by istr404** [jbara2002/windows-defender-remover#3]
hello,
nice app!
however, i executed the program and typed "n", just to disable defender and now i cannot execute the program again, because it is prohibited and i am wondering what is the intelligence that prohibits the execution?
i would appreciate your help!

**Comment by istr404** [comment]
update: i managed to execute the application, but security settings etc are not coming back...

**Comment by jbara2002** [comment]
UPDATE: The problem is fixed in version 10.0. 
In precedent versions, sgrm broker and windows security service are removed, and NOT DISABLED, you must install WIndows using in-place upgrade method, and applying again the script with "n" (disable) and "y" (enable) and it start to work.
