### ISSUE TITLE
"Remove Windows Defender and connected Windows Security Components" Option cause Microsoft Store third party apps can't uninstall

### ISSUE THREAD

**Issue by chuck00000** [jbara2002/windows-defender-remover#32]
"Remove Windows Defender and connected Windows Security Components" Option cause Microsoft Store third party apps can't uninstall, only Microsoft built in store apps can normally uninstall. Both windows 10 & 11 have this issue. After remove Windows Defender and connected Windows Security Components , system restore can't  recover removed security Components , update machine can't fix security Components. Need reset PC, only disable Windows Defender Antivirus, uninstall Store apps is back normal

![Screenshot (29)](https://user-images.githubusercontent.com/98159699/218433441-ea5bc7b3-e4de-443f-9490-49926273db58.png)

![Screenshot (28)](https://user-images.githubusercontent.com/98159699/218431205-727991c9-b3c5-4fd8-98dd-49c4cbd5df46.png)

**Comment by chuck00000** [comment]
I said both Windows 10 & Windows 11 has this issue. I'm using Windows 11 latest Dev build 25295; 

I tested on Windows 10, same issue

**Comment by jbara2002** [comment]
i didn't see the issue. so in lastest insider builds the issue is not present.. but I will not close this issue, now

**Comment by jbara2002** [comment]
in lastest version of script, this does not affect the application uninstalling in Windows 11 and even in 10.

**Comment by jbara2002** [comment]
re-opening the issue, because its happen in 12.0 and 12.5 beta!

**Comment by chuck00000** [comment]
Also, Apps from Microsoft Store can't be updated because of this.

**Comment by XBadFellaX** [comment]
I am having an issue Re-Enabling Defender and Components as well. My Windows Security App is coming up Black and this happened after I used the Script to Disable Windows Defender and Security components.

Now when I tried to re-enable it because I was getting a lot of errors in Windows Events I get the error ERROR: The process "Smartscreen.exe" not found. The system cannot find the file specified.

I don't know what to do, I have tried so many fixes from online but nothing works, and I really don't want to re-install windows.

![image](https://user-images.githubusercontent.com/77979578/226125956-5c71b095-d635-49d5-8a1d-6fffa49555bc.png)

![2023-03-18_12-05-37](https://user-images.githubusercontent.com/77979578/226125981-4178ff93-384e-4ea7-8755-287f30ef3e04.gif)

**Comment by XBadFellaX** [comment]
Unable to start a DCOM Server: {A463FCB9-6B1C-4E0D-A80B-A2CA7999E25D} as Unavailable/Unavailable. The error:
"2147942402"
Happened while starting this command:
C:\Windows\System32\smartscreen.exe -Embedding

**Comment by jbara2002** [comment]
so maybe is caused by removal of the smartscreen.. so i will check.. i'll put in 12.1, because i want to re-organize the code..

**Comment by jbara2002** [comment]
the script is unregistering the classes of the smartscreen , by removing the following registry values

[-HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]

[-HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]

so restoring them it will fix the issue.

**Comment by jbara2002** [comment]
i'll provide a reg file which is adding that values back into windows later today. So it will apply with PowerRun, and reboot. This is will be the solution of this issue.

**Comment by XBadFellaX** [comment]
Thank you!

**Comment by XBadFellaX** [comment]
Hi Jbara, Just wondering if this reg file is ready yet?

**Comment by XBadFellaX** [comment]
@jbara2002

**Comment by jbara2002** [comment]
Save into registry file and reboot the pc.
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

```
