### ISSUE TITLE
Stolen badge

### ISSUE THREAD

**Issue by farag2** [jbara2002/windows-defender-remover#33]
Why did you steal the badge from https://github.com/dragonflydb/dragonfly? You do not compile anything at your repo. You just destroy users' systems with your trojan.

```![ci-tests](https://github.com/dragonflydb/dragonfly/actions/workflows/ci.yml/badge.svg)```

![ci-tests](https://github.com/dragonflydb/dragonfly/actions/workflows/ci.yml/badge.svg)

@dragonflydb, @romange, for your notice.

**Comment by romange** [comment]
Thanks @farag2 .  Weird choice either. How it serves him to use someone else's badge?
Also not sure what I can do about it 🤷🏼

**Comment by farag2** [comment]
@romange  Nobody knows...

> Also not sure what I can do about it

Nothing. Just live with it :)

**Comment by jbara2002** [comment]
badge removed now from readme.md.
