### ISSUE TITLE
Warning , >> Verify

### ISSUE THREAD

**Issue by icy0007** [jbara2002/windows-defender-remover#36]
[{xxx-xxx-xxx}.txt](https://github.com/jbara2002/windows-defender-remover/files/11087044/xxx-xxx-xxx.txt)

**Comment by jbara2002** [comment]
{01afc156-f2eb-4c1c-a722-8550417d396f}  is the provided example for you which is going to Security and Maintenance Control Panel Applet. This is removed toghether with Windows Security Application. 
The app is removing the classes which is provided for Windows Defender Security, Windows WebThreat Service and SmartScreen. For now the added rules its not interfering with the normal usage of OS. 
The rules are constantly verified, and if existing problems, which i can't discover or you can explore deep and see any problems, this can be reported into **Issues** section into the project.
