### ISSUE TITLE
Cmd arguments

### ISSUE THREAD

**Issue by jamiekarvans** [jbara2002/windows-defender-remover#37]
Hey thanx for the code and what arguments can I use to disable defender without any cmd screen poping up or asking for key to press.
And also how did you packed all the files into exe? Also is there any argument for Remove but not immediately force restart but instead just waiting for system to restart by user and then continue the script or completeling the removing process.

**Comment by jbara2002** [comment]
Thanks for writing. Normally is ``` /R ``` to remove Defender. You can't remove without restart because after applying the script, the services are running and it's mandatory to restart. After restart, the components are not running. Another variant is to schedule an restart by user, if that is requested by user, and this is not added.

**Comment by jamiekarvans** [comment]
Hi thanks for reply,
Unfortunately the command /R will pop up an script and asks for what to do which I have to press Y or R to remove all of it and start the script
What I want actually is to avoid this screen popping up and automatically remove or disable the defender by just doing the command DefenderRemover.exe /R so there is no need for user interaction, technically I just want to automate it and would be nice so that there would be no force restart and the script waits for user to restart the PC itself

**Comment by jbara2002** [comment]
My wrong, the remover argument is ``` /Y ``` not ``` /R ```.

**Comment by jamiekarvans** [comment]
thanx it fixed the problem,
but still the cmd screen is popping up and i wanted to avoid that screen
do you have any suggestion for me? maybe if i can add a code to the script and compile again?

**Comment by jbara2002** [comment]
you can try lastest release, for now. it partial improve what are you saying.
