### ISSUE TITLE
Pin code broke and windows became unusable

### ISSUE THREAD

**Issue by NudeNULL** [jbara2002/windows-defender-remover#39]
Windows version: Windows 11 Home Build 22621
Device: Galaxy Book3 Pro

Used different versions of defender removal, the H option, and after restart the windows is showing that I have to reset the pin, clicking set up pin again is not doing anything and I am stuck at lock screen. Only restore to a restore point or fresh windows install helps.

**Comment by jbara2002** [comment]
Thanks for writing. I'll search for the cause for the problem.
Maybe is affecting something about TPM Usage or Microsoft Pluton. When PIN Broke, you must change to type the password , remove the PIN and re-add in Accounts Settings.
For now, i'll note this a issue. If the problem is appearing, i'll provide a solution or i'll put a fix into script.

**Comment by NudeNULL** [comment]
I tried using other sign in method but I don't have such option. Will try to remove pin.![PXL_20230503_083854239~2.jpg](https://user-images.githubusercontent.com/15786742/235869532-86e92062-1b7b-4dd1-8408-69508c0c65dc.jpg)

**Comment by NudeNULL** [comment]
Removing pin helped, logged in with password, then set the pin again

**Comment by NudeNULL** [comment]
Trying to set a new Pin, looks like some module related to this is disabled and I can't set it, and always have to use the password, will be there a fix so I can use Pin?

On other PC's that were updated to this version of windows the pin still works, and the defender was removed the same way using the H option in the past.

It just breaks if trying to use this feature on fresh latest windows install.

Also I can't install an older windows 11 version..it forces me to connect to a network and it updates itself to the latest version.

If you know how can I install an older official image of windows 11 that does not require internet connection let me know.

**Comment by jbara2002** [comment]
you can reinstall windows 11 without internet connection. 
after the appearing of the oobe home page (Select region message) , press ``` Shift+F10 ``` and a command prompt window it will open.
in command prompt write ``` oobe\bypassnro ``` and the pc will reboot. After reboot set your pc and in network page  ``` i don't have internet ``` it will appear.
