### ISSUE TITLE
Не полное удаление

### ISSUE THREAD

**Issue by D1mar0n** [jbara2002/windows-defender-remover#4]
Hello! Yesterday I tested your script on Windows 11 x64 Pro (just installed). After running the script, I waited for the end and the system rebooted. When you turn on the PC, Window Defender is not detected, but there is a shortcut from this application in the Start menu. Can you fix your script a little so that it removes all traces of the Defender? Thanks in advance for your reply.

**Comment by jbara2002** [comment]
The shortcut of the application, maybe its Windows Security Center. If  the shortcut is from Windows Security Center, go to Settings, Apps , and find the app. After that click Reset. The shortcut will disappear.

**Comment by NinelieZ** [comment]
It seems that this issuse comes back on 22621.1555, I tried the ver12.4 twice but the icon still exist and there is no Security Center apps in Settings.

**Comment by jbara2002** [comment]
issue reopened.
