### ISSUE TITLE
[Bugs] Remover will break updater from Microsoft Store

### ISSUE THREAD

**Issue by IRedDragonICY** [jbara2002/windows-defender-remover#42]
Remover Version: release_def_12_4_1
yes, new update UWP apps run nicely, but cannot update from Microsoft Store.

![image](https://user-images.githubusercontent.com/98265563/236599610-aa6b62db-a260-45d7-85ff-6c68c114da2a.png)
![image](https://user-images.githubusercontent.com/98265563/236599797-3d553de7-5823-41cb-9149-c531079a3597.png)

Here logs
[logs.zip](https://github.com/jbara2002/windows-defender-remover/files/11411260/logs.zip)

**Comment by jbara2002** [comment]
hi.. after tested 12.4.1 in lastest Canary, Dev and 22H2 builds , it doesn't have problems with MSStore. 
The case from the problem was smartscreen classes unregister, so in 12.4.1 smartscreen will not be unregistered because it produces problems with uwp.
After upgrading and reinstalling the OS, the downloads it works for now.
Thanks for logs. I'll look and do deeper troubleshoting to solve the issue.

**Comment by jbara2002** [comment]
have you applied another version of the script before?

**Comment by IRedDragonICY** [comment]
Yes, from disable to remove.

**Comment by jbara2002** [comment]
okay. i'll provide registry keys to re-register the components in this issue report to make uwp download to work again. this is take a while.

**Comment by khealou** [comment]
release_def_12_4_1
Same here, Apps run fine but unable to update through Windows Store.
My first time using the tool on my Windows 11
![Untitled](https://user-images.githubusercontent.com/8231128/236697823-cb5bfa80-0337-4055-893e-7745f162e5eb.png)

![Untitled2](https://user-images.githubusercontent.com/8231128/236697831-7b945fff-cfe0-497b-9059-22978b109b14.png)

**Comment by jbara2002** [comment]
what version of Windows 11 will have? 21H2 or 22H2 or Moments?

**Comment by khealou** [comment]
> Windows 11 22H2 22624.1690

**Comment by khealou** [comment]
Windows 11 22H2 22624.1690

**Comment by IRedDragonICY** [comment]
> Windows 11 22H2 22624.1690 Edit : Where can I find the logs for this?

Event Viewer

**Comment by ad1tya2** [comment]
Does anyone have a fix for this issue? 
I ran the remove option 'Y' and its completely broken
Right now microsoft store is working but cannot uninstall or update anything, only install works.

**Comment by localip** [comment]
> okay. i'll provide registry keys to re-register the components in this issue report to make uwp download to work again. this is take a while. this will fix the issue.

Any news on this?

**Comment by localip** [comment]
🤔 
https://github.com/jbara2002/windows-defender-remover/assets/98427312/bae6c751-be38-4f66-9278-7cb03066bf41

**Comment by localip** [comment]
🤔 

https://github.com/jbara2002/windows-defender-remover/assets/98427312/d91b7193-564e-45cb-8764-0ddd55027478

**Comment by jbara2002** [comment]
fixed in 12.4.6. Download Hotfix1 from release, open as Admin and Reboot.
