### ISSUE TITLE
Breaks NTLMv2 Authentication (Network shares)

### ISSUE THREAD

**Issue by Mnky313** [jbara2002/windows-defender-remover#44]
The current script adds a registry entry for:

[HKLM\SYSTEM\CurrentControlSet\Control\Lsa]
LmCompatibilityLevel=dword:00000002

This breaks network shares that don't allow NTLMv1.
(shares will return incorrect password)

I'm not sure why this is changed as removing the entry fixes problems with connecting to shares.

**Comment by jbara2002** [comment]
ok. so apply the script without that registry value, it will solve the issues with NTLMv1?
i'm asking you because i don't use Network Shares

**Comment by Mnky313** [comment]
Yes, If you remove the line that adds that entry it should work.

I also removed the entries for:
[HKLM\SYSTEM\CurrentControlSet\Control\Lsa]
"RestrictReceivingNTLMTraffic"=dword:00000002
"RestrictSendingNTLMTraffic"=dword:00000002

But after added them back it appears to still work, though If I'm reading their documentation correctly this should block sending and receiving NTLM traffic which might break other stuff like RDP.

https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-incoming-ntlm-traffic

**Comment by jbara2002** [comment]
ok. thx for noticing. i'll modifying the code and re-release a subversion.

**Comment by jbara2002** [comment]
fixed in 12.4.2. When you apply the removal script. That value will be not added anymore.
