### ISSUE TITLE
start menu broken

### ISSUE THREAD

**Issue by benapetr** [jbara2002/windows-defender-remover#46]
Hello,

This app is great, it increased the performance of my low end laptop incredibly! There is just one small issue, ever since I did this start menu is misbehaving a lot (it was almost clean windows install I did it on).

Sometimes it doesn't open at all when I click it, sometimes it just takes a long time for it to open, search bar is completely broken, when I click it, it disappears, and sometimes it crashes.

I also noticed that after login it takes very long time for whole taskbar to appear. I think this started happening after I installed last windows updates. Did anyone else experience this? Is there a fix?

**Comment by jbara2002** [comment]
hi. it looks you're are first user which expected this problem. Can you say what windows version have you used to apply this script?

**Comment by ad1tya2** [comment]
I recently had the same issue
Earlier i had used the removal option for windows defender
it worked fine for quite a while but after some windows update exactly what you said started happening and store apps also stopped working.
I did a clean reinstall and then i again used the remove option since i hadnt figured out the source of the issue, only when I used the removal option again i saw UWP apps were broken again, but after a clean install although you cant uninstall or update UWP apps the late loading of the entire windows explorer process will be fixed.

It seems like the removal script is removing an necessary registry entry

**Comment by benapetr** [comment]
Hello

Microsoft Windows [Version 10.0.22621.1702]

I will try to get version from about once I get it to open xD it's not easy with no start menu

**Comment by benapetr** [comment]
This is from event viewer (really hard to copy paste, I can either make a screenshot or get very long XML):

```
The program SystemSettings.exe version 10.0.22621.1635 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
---
Fault bucket 1864226002042980745, type 5
Event Name: MoAppHang
Response: Not available
Cab Id: 0

Problem signature:
P1: windows.immersivecontrolpanel_10.0.6.1000_neutral_neutral_cw5n1h2txyewy
P2: praid:microsoft.windows.immersivecontrolpanel
P3: 10.0.22621.1635
P4: 12963a0f
P5: 71bf
P6: 4194304
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ec141eb0-c735-4ee1-bbbd-e96ce1931ceb.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6b8a9c4c-2d4b-48ab-bb29-bc203fc24256.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.feebfc2c-b136-414e-b149-38675c7496b5.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.af184299-98d8-4a04-907c-71f0568c81d8.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_windows.immersiv_88412bc220b4692c8bfccc33995cf53323775f_06ae74d7_068edc85-c668-473b-b08b-563f6be78b8c

Analysis symbol: 
Rechecking for solution: 0
Report Id: ecb3d3dd-dad1-4aee-9c0f-bfcd08cca3d2
Report Status: 268435456
Hashed bucket: 09bfe2c60a89adad49df0fabf8d18989
Cab Guid: 0
---
Successfully scheduled Software Protection service for re-start at 2123-04-22T07:48:32Z. Reason: RulesEngine.
--
The shell stopped unexpectedly and explorer.exe was restarted.
--

```

It seems that OS is still trying to interact with antivirus service which is missing

**Comment by benapetr** [comment]
so, I ran into some BSOD problems later, ran into system recovery, which did some black undocumented magic. Now system looks like it's OK, everything works as expected and bit defender is still gone, so it's all perfect

**Comment by acurvers** [comment]
> ran into system recovery

what did you do exactly i also have this problem with the start menu and search, i would like to fix @benapetr
