### ISSUE TITLE
No instructions on what to run and how to make it run

### ISSUE THREAD

**Issue by staurosKaragiannis** [jbara2002/windows-defender-remover#5]
In README.md , it says "Just run the app." but what is the "app"? what am i supposed to run exactly? it makes sense to run melody.exe but this is what it does:

```
-------------------------------------------
--------Registry Tweak Tool v1.4.7.0-------
---------------for Windows 6.x-------------
---------Created by Michal Wnuowski--------
-----Concept by Aviv00@msfn / lite8@MDL----
-----------Modified by Legolash2o----------
-------------------------------------------

Type path to mounted install.wim :

```

What? what path?? it closes when i type anything.

I think it needs better and more clear instructions on how to use this.

**Comment by OVERPEY** [comment]
you should download it from [release ](https://github.com/jbara2002/windows-defender-remover/releases/tag/release_def_10_1) section (NOT the source code).

**Comment by jbara2002** [comment]
Hi. You must to download the script from release section. This is source code of the application (including components such as melody.exe and PowerRun).
I will update the homepage and will make instructions more clearer and a FAQ Section soon.😄

**Comment by staurosKaragiannis** [comment]
Oh my bad :roll_eyes:, i didn't know that i had to download it from somewhere else :smile:. Thanks.

**Comment by jbara2002** [comment]
no problem... =)  You're welcome!
