### ISSUE TITLE
win securety icon in start menu

### ISSUE THREAD

**Issue by pnrxtx** [jbara2002/windows-defender-remover#52]
Hello, i did "remove windows defender and security components". Everything was removed apart from shortcut icon from start menu. Cant find a way to remove it. Very minor issue and can be ignored, but for perfection of looks would like to find a way to get rid of it :)
![1111](https://github.com/jbara2002/windows-defender-remover/assets/88897538/df6cbab2-ce1c-4797-912c-139331bb8ac9)

**Comment by jbara2002** [comment]
i've seen recently that. that's why i skipped the launch of version 12.4.5.

**Comment by jbara2002** [comment]
fixed in 12.4.6
