### ISSUE TITLE
Microsoft store app not working

### ISSUE THREAD

**Issue by sharicov** [jbara2002/windows-defender-remover#53]
Microsoft store app stopped working since previous version of defender remover was ran, today's UWP fix doesn't help (ran as administrator just in case)

![image](https://github.com/jbara2002/windows-defender-remover/assets/1933626/ab14ffa1-e033-4032-bec8-3363b50735d7)

**Comment by ad1tya2** [comment]
yes i can confirm, it is still returning the same error

**Comment by TakiiiNotFound** [comment]
same issue over here

**Comment by sm1ly** [comment]
got the same problem.
also if I download last windows update - it brokes explorer totally. and its about defender remover((
