### ISSUE TITLE
UWP-based Apps broke after removed Windows Security

### ISSUE THREAD

**Issue by mrzrk67** [jbara2002/windows-defender-remover#54]
Photo and other UWP-related app doesn't work anymore after remove Security from Windows, applied hotfix1_uwp. exe DOES NOT fix the issues either.

**Comment by jbara2002** [comment]
i'm looking deeper for this issue. In Windows 11 22H2 and lastest Insider Builds (Dev & Canary) this are worked fine.

**Comment by Smok1e** [comment]
Same here

**Comment by Smok1e** [comment]
Updates and store are also broke

**Comment by stimpy81** [comment]
Still an ongoing issue.  It just broke my fresh install of Win11 build 23466.1001
![image](https://github.com/jbara2002/windows-defender-remover/assets/134618448/71b671ca-49ef-4c30-bd0c-d8008554e62c)

**Comment by jbara2002** [comment]
create a reg file with following values

``` Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
@="SmartScreen"
"AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
@="C:\\Windows\\System32\\smartscreenps.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
@="C:\\Windows\\System32\\smartscreen.exe"
```
 _Apply with PowerRun or run as TrustedInstaller._

**Comment by stimpy81** [comment]
> create a reg file with following values
> 
> ```
> 
> [HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
> @="SmartScreen"
> "AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"
> 
> [HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
> @="C:\\Windows\\System32\\smartscreenps.dll"
> "ThreadingModel"="Both"
> 
> [HKEY_CLASSES_ROOT\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
> @="C:\\Windows\\System32\\smartscreen.exe"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
> @="SmartScreen"
> "AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
> @="C:\\Windows\\System32\\smartscreenps.dll"
> "ThreadingModel"="Both"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
> @="C:\\Windows\\System32\\smartscreen.exe"
> 
> [HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
> @="SmartScreen"
> "AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"
> 
> [HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
> @="C:\\Windows\\System32\\smartscreenps.dll"
> "ThreadingModel"="Both"
> 
> [HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
> @="C:\\Windows\\System32\\smartscreen.exe"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}]
> @="SmartScreen"
> "AppID"="{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\InProcServer32]
> @="C:\\Windows\\System32\\smartscreenps.dll"
> "ThreadingModel"="Both"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a463fcb9-6b1c-4e0d-a80b-a2ca7999e25d}\LocalServer32]
> @="C:\\Windows\\System32\\smartscreen.exe"
> ```
> 
> _Apply with PowerRun or run as TrustedInstaller._

I created a .reg file after copy and pasting this into a reg file.  However after downloading PowerRun v1.6 after adding the .reg file to PowerRun when I run it I get a error...

![image](https://github.com/jbara2002/windows-defender-remover/assets/134618448/b11a9306-97f7-4672-8684-09c98a3662a8)

**Comment by jbara2002** [comment]
put 
` Windows Registry Editor Version 5.00 ` in first line

**Comment by jbara2002** [comment]
this is the listed key

**Comment by stimpy81** [comment]
OK, many thanks!  Adding that line got rid of the error.  I notice that even after a restart that SmartScreen.exe is still running, is this normal?

**Comment by jbara2002** [comment]
re-register smartscreen classes in Windows
