### ISSUE TITLE
ISO creating failing

### ISSUE THREAD

**Issue by adolfotregosa** [jbara2002/windows-defender-remover#55]
Can't seam to create the iso. The folder with iso c:\defenderRemovedISO\WindowsDefenderRemovedImage.iso never shows up.

![win11_1](https://github.com/jbara2002/windows-defender-remover/assets/7437931/d08dbd42-0363-4f78-8add-dd8f323fed73)

Windows 11 22h2 22612.1776

**Comment by jbara2002** [comment]
thx for providing. sometimes the iso creator can be buggy, so i will check if it something wrong with OSCDIMG integration first.
