### ISSUE TITLE
Files not found errors

### ISSUE THREAD

**Issue by stimpy81** [jbara2002/windows-defender-remover#56]
Thank you for this wonderful tool!

I just made a fresh install of Windows 11 build 23466.1001, installed drivers and ran this tool (v12.4.6).  I selected option Y, and it brought up a powershell/terminal screen, which was full of red text.  It was only on the screen for seconds, but I managed to read that it was missing many files.

After Windows restarted it seems to be working ok so far, and the Defender icon is gone.

But I'm guessing that the Windows install is now damaged due to this tool leaving the job only partially completed.

If there is a log file on my computer, tell me where it is, and you can have it.

**Comment by jbara2002** [comment]
I´ve seen that red 2 messages for me. First is the Windows Security App (Security Center App) can not found, and second thing, `.ps1` file can not be found. It this not an problem for now.

**Comment by stimpy81** [comment]
> I´ve seen that red 2 messages for me. First is the Windows Security App (Security Center App) can not found, and second thing, `.ps1` file can not be found. It this not an problem for now.

Yeah, I have encountered 0 issues so far, I guess the test will be when Windows updates to the next build.  If it's a problem, or find any issues, then I will update here.

**Comment by stimpy81** [comment]
OK, I can report that Microsoft Store Apps will not update.

**Comment by jbara2002** [comment]
no. there errors cause by some rules of remover (security center or smartscreen) for that is trying to found a solution
