### ISSUE TITLE
Windows defender not disabled properly in versions greater than 12.4++

### ISSUE THREAD

**Issue by IRedDragonICY** [jbara2002/windows-defender-remover#58]
If using version 12.3, Windows Defender shuts down properly. While version 12.4 and above, the antimalware service is still running on taskmgr.
affected option:
- n (disable)
- h (disable with security component)

**Comment by jbara2002** [comment]
ok. i'm trying to make the remover part tp work to the store and i've seen the 12.3.1 remover is not inteffering with the store ans uwp.
