### ISSUE TITLE
[Critical Bug] Criticall Process Died after remove Windows Defender

### ISSUE THREAD

**Issue by IRedDragonICY** [jbara2002/windows-defender-remover#6]
Version: Insiders Beta 22621
SKU: Windows 11 Pro for Workstation
Bug generate: After Windows Startup, localservicenonetworkfirewall recall about windows defender service that make cpu usage higher. After a few second, greenscreen with error code critical process died.
suggestion: I recommend also turning off localservicenonetworkfirewall, im think that works.
![Screenshot_2022-09-07-11-45-26-309_com miui gallery-edit](https://user-images.githubusercontent.com/98265563/188790799-d013b25b-7468-4bc4-91b3-c5fed413f416.jpg)
![Screenshot_2022-09-07-11-46-18-688_com miui gallery-edit](https://user-images.githubusercontent.com/98265563/188790889-58ba05ee-3310-48eb-88a3-058fd49889ef.jpg)

**Comment by jbara2002** [comment]
Ah. It's not critical, after getting the error ,reboot and  try again to apply the script and the error will not appear. (Maybe it stopped the processes for SmartScreen Service or Anti-Malware Service was stopped by the script).  ț
