### ISSUE TITLE
MS Store and UWP apps are not downloading and updating

### ISSUE THREAD

**Issue by iam-thedude** [jbara2002/windows-defender-remover#60]
Hi!

Thanks for your great tool!

But unfortunately, after disabling Defender using "N" button MS Store stops updating and downloading apps.
I tried turning off Smart App Control and using UWP Fix V1, nothing helped (including re-enabling Defender using your app).

By the way, even after re-enabling Defender i can't find Smart App Control/Smart Screen Tab in settings (it appears in Search but it is not opening).

Also, i tried REG file you provided earlier here (using PowerApp) to re-register Smart Screen/SAP and it didn't helped either.

Any possible fixes?

Many thanks!

W11 Pro 22621.1778 Stable build.
App version 12.4.6

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/d5c55ceb-e0be-4376-abcc-1901aa0ff456)

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/4fd891ba-2c0a-4d0e-91ec-0e82373bcd99)

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/1cabd881-dc88-4236-8537-35baac71797c)

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/d0ba0cbc-8cb1-49ff-bbf0-3851221bb7bb)

**Comment by iam-thedude** [comment]
And i noticed that MS Store service is running but after i'm trying to update or download any app using MS Store it is disabling by itself.

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/7612a606-d666-4ac3-b672-d04f03bb01f0)

**Comment by iam-thedude** [comment]
And there is one error occurring using "I" button.

![image](https://github.com/jbara2002/windows-defender-remover/assets/107628183/fa0ea0f8-77d9-4ebf-8476-337947f8ab35)

**Comment by antonioivanov6** [comment]
Hello!
Same problem here. I use "Y" option and now MS Store is bricked.

**Comment by guitarhero7** [comment]
yup, cant unninstall any windowss app here

**Comment by jbara2002** [comment]
https://github.com/jbara2002/windows-defender-remover/releases/tag/pre_def_12_5

**Comment by d3adwolf** [comment]
The same error on both the stable release and the pre-release. Error in MS Store: 0x80073CF9.

**Comment by jbara2002** [comment]
ok. i've seen this week by applying in Windows 11 21H2 VM. Checking the cases, and fix.

**Comment by BurntDog** [comment]
Wow, you need to stop spamming issues and lower that post count.
