### ISSUE TITLE
Report test of Defender Remover 12.5

### ISSUE THREAD

**Issue by jbara2002** [jbara2002/windows-defender-remover#62]
This is the page of report page to apply the Script to fix MS Store and UWP Bugs.
Testers will write a report like that:
Phase n: OK (if MS is working) or NOT OK (if MS Store Bricks). (n is 1 to 5, noted as ****DefenderRemover.Phanse.n.exe****

**Comment by sm1ly** [comment]
Hello mate!
You are doing really important thing!
Thanks a lot.
So my story:

Got system:
Edition:    Windows 11 Pro
Version:    22H2
OS build:   22621.1702
Expirience: Windows Feature Experience Pack 1000.22641.1000.0

Installed 12.4. UWP brokes. Cant use calc, photos, paint.
Try your fix. Doesnt help.
Try yesterday update:
Phase 1: OK

But. Here is the next problem/ If I update to next cummulative patch from 2023-05. Explorer brokes. msappx uses 50+ % CPU. cant check version or recovery (only over F8 in reboot). So disable updates and use OS build: 22621.1702.

Thanks for your work !

**Comment by xsm1997** [comment]
Windows 11 22H2 insider beta (build 22631.1830). Tried fresh installed VM and physical machine.

Phase 1: OK
Phase 2: OK
Phase 3: OK
Phase 4: OK
Phase 5: OK

No problem with 12.5, even with 12.4.6. MS Store can open, UWP app works normally, and apps can be uninstalled.

**Comment by Tree1527** [comment]
> > Edition: Windows 11 Pro Insider Dev Version: 22H2 OS build: 25352.1 Experience Pack: Windows Feature Experience Pack 1000.25350.1000.0:
> > Installed 12.4. UWP apps open and work MICROSOFT STORE UPDATE BROKEN UWP APPS UNINSTALL BROKEN
> > UWP Fix Did not work 12.5: Phase 1: NOT OK Phase 2: NOT OK Phase 3: NOT OK Phase 4: NOT OK Phase 5: NOT OK
> 
> but about 12.3.1? i don't testing, but i heard some people the 12.3.1 is uwp and msft store are working.

nope this does not fix this issue either
infact it makes it worse by breaking UWP apps from even opening

**Comment by jbara2002** [comment]
what?  **breaking UWP apps from even opening?** explain

**Comment by moitinhdaukiss** [comment]
Windows 11 Enterprise G 22621.1830 
4. OK
5. OK
But is there any solution to remove the icon in the Start Menu?

**Comment by system-18** [comment]
Sorry. It seems like I need to recover what has been deleted when I used it. Now my computer is having some issues when using **DefenderRemover.Phase5.exe** Is there any way for me to restore what it has done?

**Comment by jbara2002** [comment]
> Windows 11 Enterprise G 22621.1830 4. OK 5. OK But is there any solution to remove the icon in the Start Menu?

yeah  right click on proprierties and click Reset and reboot. (re -register Windows Security Center App)

**Comment by xsm1997** [comment]
> Windows 11 22H2 insider beta (build 22631.1830). Tried fresh installed VM and physical machine.
> 
> Phase 1: OK Phase 2: OK Phase 3: OK Phase 4: OK Phase 5: OK
> 
> No problem with 12.5, even with 12.4.6. MS Store can open, UWP app works normally, and apps can be uninstalled.

Updated to Windows 11 insider beta build 22631.1835, and MS store is broken. Will do further test.

**Comment by jbara2002** [comment]
According to your reports, the result is different. So maybe making a ``` safe ``` version of Remover (removing services, associations, startup entires and tasks, and uac enabling) it will solve the issue. Also the current method will be kept, if you want a deeper remove of Windows Defender. About the method: for me ms store and uwp are working if is safe of deeper removed. I will modernize a script a bit, because i finalised the research of Defender values, data and information store. So big thanks!

**Comment by sm1ly** [comment]
okey, I updated to latest build which I cant see, cause it's doesn't show it. 
I tested all the phases.
I cant restart system on phase 5, all the phases doesn't work with this build
and I found and issue.
![PXL_20230618_174914332](https://github.com/jbara2002/windows-defender-remover/assets/127539757/d258d7c3-80c1-4f24-b195-1ca2724397d7)

**Comment by jbara2002** [comment]
it referes about  UWP Removal. So in 12.5 will be not removing via `.ps1` filw anymore.
The release of 12.5 will be somewhere next week, after that. bugfixing if bugs exists.

**Comment by jbara2002** [comment]
OK. This feed will be closed. Thx for helping and contribuing for the app 💛!
I am working for a new version of the app.

**Comment by morrowindmemes** [comment]
Will the 12.5 release solve the problems for those who completely erased defender from their systems? I tried everyhing in this repo and all "Phase .exe's" but it didn't help. Can't delete or install any UWP app. I'm on  Win11 22H2 Build 23493.1000.
