### ISSUE TITLE
Microsoft Store and Windows Security updates are not Installing

### ISSUE THREAD

**Issue by anurag-2008** [jbara2002/windows-defender-remover#63]
![image](https://github.com/jbara2002/windows-defender-remover/assets/136780306/6e31fe29-a9e8-4b1b-b963-ec6e13e06d5d)
![image](https://github.com/jbara2002/windows-defender-remover/assets/136780306/a6cb2c7d-119b-432a-b442-f3ea1ffab12b)
![image](https://github.com/jbara2002/windows-defender-remover/assets/136780306/77b70d0d-dbe1-4884-9498-ab6ecc8d5e7b)

After Disabling Windows Defender this problems I am experiencing and able to update apps. Please tell how can I fix this issue.
I also tried SFC /SCANNOW but this is also not working.
What can I do plz tell me...

**Comment by jbara2002** [comment]
noted. i'll check if this happens of affects the same.

**Comment by HAMODE3389** [comment]
Is there any fix for this? ( Microsoft Defender update install error 0x80070643 ).
