### ISSUE TITLE
fuck up my pc (help fix plz)

### ISSUE THREAD

**Issue by Hhghfffddfj** [jbara2002/windows-defender-remover#9]
Windows defender has been annoying me for a while. having to disable it a million times i downloaded this software and pressed Y to delete windows defender. good windows defender is gone but now I cant upgrade my windows version, reset pc, when i try to redownload windows defender your program automatically closes chrome, i even tried windows iso file to reset it and it was automatically close. I'm stuck on this version of windows. any fix for this?

**Comment by Hhghfffddfj** [comment]
after troubleshooting windows update I got this "Some security settings are missing or have been changed" 
ran "%SYSTEMROOT%\SYSTEM32\REGSVR32.EXE %SYSTEMROOT%\SYSTEM32\WUAUENG.DLL"
got "entry point DillregisterServer was not found

**Comment by jbara2002** [comment]
1. Download lastest Windows 10 ISO from Microsoft and run the setup.exe and do the upgrade (the process is named Upgrade in-place). All the data , documents and programs are keeped in this process. 
2. Wait for the v11 release for the script. It will come with that fix.  Re-apply , and will not have defender.  
3. After reboot, the OS must work with correct parameters.
